"""One-time backfill: regex-scrapes the real, currently-live docs/*/index.html
hub pages (built by the old update_hub_pages.ps1 surgical-mutation approach)
into the new data/Characters/{Name}/index.json + data/site_index.json model,
then immediately re-renders from that JSON and diffs against the real live
pages - that re-render-and-diff *is* this tool's own parity test, per the
migration plan. Not a live code path - used once per healer, then done.

Every recovered bosses_killed is cross-checked against the real
{code}_report_data.json where one exists (the same "prefer real data over
scraped/passed text" pattern the original update_hub_pages.ps1 used at
insert time, applied here at backfill time instead). A report-code folder
with no report_data.json backing (a v1-era raid night, which predates the
JSON pipeline entirely) is tagged "source": "v1_html_backfill" so it stays
forever visible in the data which entries were mechanically recovered from
HTML versus generated by the real pipeline.

site_index.json's healer list is built ONLY from healers actually linked in
the real, live docs/index.html - this preserves any deliberately-unlisted
healer (e.g. Turkeykin, kept direct-URL-only per explicit instruction) as
unlisted, without needing a special case: her own hub page still gets a
real index.json and gets re-rendered, she just never appears in
site_index.json because she was never linked from the real docs/index.html
to begin with.
"""

from __future__ import annotations

import argparse
import re
from datetime import datetime
from pathlib import Path

from pipeline import hub_pages
from pipeline import jsonio

RAID_ROW_RE = re.compile(r'<a class="raid-row"\s+href="([^"]+)/index\.html">(.*?)</a>', re.DOTALL)
RAID_TITLE_RE = re.compile(r'<div class="raid-title">(.*?)</div>', re.DOTALL)
RAID_META_RE = re.compile(r'<div class="raid-meta">(.*?)</div>', re.DOTALL)
HEALER_ROW_RE = re.compile(r'<a class="healer-row"\s+href="([^/]+)/index\.html">', re.DOTALL)
DATE_FROM_META_RE = re.compile(r'^(.*?)\s*&nbsp;(?:&middot;|·)&nbsp;\s*report', re.DOTALL)


def _parse_date_text(date_text: str) -> str | None:
    date_text = date_text.strip()
    for fmt in ("%B %d, %Y", "%m.%d.%Y", "%Y-%m-%d"):
        try:
            return datetime.strptime(date_text, fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue
    return None


def _parse_bosses_label(label: str) -> tuple[int, int]:
    """Best-effort parse of 'N bosses killed' / 'N boss killed' / 'K/M bosses'."""
    m = re.match(r"(\d+)\s*/\s*(\d+)\s*bosses", label)
    if m:
        return int(m.group(1)), int(m.group(2))
    m = re.match(r"(\d+)\s*boss(?:es)?\s*killed", label)
    if m:
        n = int(m.group(1))
        return n, n
    return 0, 0


def scrape_healer_hub(hub_html_path: Path) -> tuple[str, str, str, str, list[dict]]:
    """Returns (character_name, class_spec, server, region, raid_nights)."""
    html = jsonio.read_text(hub_html_path)

    name_match = re.search(r"<h1>(.*?)</h1>", html, re.DOTALL)
    character_name = name_match.group(1).strip() if name_match else hub_html_path.parent.name.capitalize()

    class_spec_match = re.search(r'class="eyebrow"><a[^>]*>.*?</a>\s*&nbsp;·&nbsp;\s*(.*?)</p>', html, re.DOTALL)
    class_spec = class_spec_match.group(1).strip() if class_spec_match else None

    server_region_match = re.search(r'class="subline">([\w]+)-([\w]+)', html)
    server = server_region_match.group(1) if server_region_match else "Dreamscythe"
    region = server_region_match.group(2) if server_region_match else "US"

    raid_nights = []
    for m in RAID_ROW_RE.finditer(html):
        report_code = m.group(1)
        block = m.group(2)
        title_m = RAID_TITLE_RE.search(block)
        raid_title = title_m.group(1).strip() if title_m else "SSC / TK"
        meta_matches = RAID_META_RE.findall(block)
        raid_date = None
        if meta_matches:
            date_m = DATE_FROM_META_RE.match(meta_matches[0])
            date_text = date_m.group(1) if date_m else meta_matches[0]
            raid_date = _parse_date_text(date_text)
            if raid_date is None:
                print(f"  WARNING: could not parse date text '{date_text}' for report {report_code} - using a sentinel far-past date.")
                raid_date = "1900-01-01"
        bosses_killed, bosses_attempted = _parse_bosses_label(meta_matches[1] if len(meta_matches) > 1 else "")
        raid_nights.append({
            "report_code": report_code, "raid_date": raid_date, "raid_title": raid_title,
            "bosses_killed": bosses_killed, "bosses_attempted": bosses_attempted,
        })

    return character_name, class_spec, server, region, raid_nights


def bootstrap(docs_root: str = "docs", characters_root: str = "data/Characters", data_root: str = "data", templates_root: str = "templates_jinja") -> None:
    docs_path = Path(docs_root)
    site_index_html = docs_path / "index.html"
    linked_slugs: set[str] = set()
    if site_index_html.exists():
        site_html = jsonio.read_text(site_index_html)
        linked_slugs = {m.group(1) for m in HEALER_ROW_RE.finditer(site_html)}

    healer_dirs = sorted(
        d for d in docs_path.iterdir()
        if d.is_dir() and (d / "index.html").exists()
    )

    site_index = {"healers": []}

    for healer_dir in healer_dirs:
        slug = healer_dir.name
        print(f"=== {slug} ===")
        character_name, class_spec, server, region, raid_nights_raw = scrape_healer_hub(healer_dir / "index.html")
        class_name = hub_pages.DISPLAY_NAME_TO_CLASS.get(class_spec)
        if not class_name:
            print(f"  WARNING: could not resolve class from class_spec '{class_spec}' - skipping {slug}.")
            continue

        raid_nights = []
        for rn in raid_nights_raw:
            report_data_path = Path(characters_root) / character_name / rn["report_code"] / f"{rn['report_code']}_report_data.json"
            if report_data_path.exists():
                real_data = jsonio.read_json(report_data_path)
                real_killed = len(real_data["Bosses"])
                real_attempted = real_data.get("BossesAttempted") or real_killed
                if real_killed != rn["bosses_killed"]:
                    print(f"  NOTE: report {rn['report_code']} - scraped bosses_killed={rn['bosses_killed']}, real report_data.json shows {real_killed} - using the real value.")
                rn["bosses_killed"] = real_killed
                rn["bosses_attempted"] = real_attempted
                rn["source"] = "v2"
            else:
                rn["source"] = "v1_html_backfill"
                print(f"  NOTE: report {rn['report_code']} has no report_data.json - tagged as v1_html_backfill (recovered from HTML only).")
            raid_nights.append(rn)

        index_data = {
            "character_name": character_name, "class_name": class_name,
            "server": server, "region": region,
            "raid_nights": sorted(raid_nights, key=lambda r: (r["raid_date"], r["report_code"]), reverse=True),
        }
        jsonio.write_json(Path(characters_root) / character_name / "index.json", index_data)
        print(f"  Wrote {characters_root}/{character_name}/index.json ({len(raid_nights)} raid night(s))")

        if slug in linked_slugs:
            cfg_display = class_spec
            site_index["healers"].append({
                "character_name": character_name, "healer_slug": slug,
                "class_name": class_name, "display_name": cfg_display,
            })
        else:
            print(f"  NOTE: '{character_name}' is not linked from the live docs/index.html - kept unlisted in site_index.json (matches the real live site's current state).")

    jsonio.write_json(Path(data_root) / "site_index.json", site_index)
    print(f"\nWrote {data_root}/site_index.json ({len(site_index['healers'])} linked healer(s))")

    print("\n=== Re-rendering from bootstrapped JSON (this IS the parity test) ===")
    for healer_dir in healer_dirs:
        character_name = None
        for d in Path(characters_root).iterdir():
            if d.name.lower() == healer_dir.name:
                character_name = d.name
                break
        if not character_name:
            continue
        index_data = hub_pages.load_healer_index(characters_root, character_name)
        if index_data:
            hub_pages.render_healer_hub(index_data, docs_root, templates_root)
    hub_pages.render_site_index(site_index, docs_root, templates_root)


def main() -> int:
    parser = argparse.ArgumentParser(description="One-time backfill of the index.json hub-page model from live docs/ HTML")
    parser.add_argument("--docs-root", default="docs")
    parser.add_argument("--characters-root", default="data/Characters")
    parser.add_argument("--data-root", default="data")
    parser.add_argument("--templates-root", default="templates_jinja")
    args = parser.parse_args()

    bootstrap(args.docs_root, args.characters_root, args.data_root, args.templates_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
